# Generated by Django 4.0.3 on 2022-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_alter_amazon_data_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_data',
            name='img',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='amazon_data',
            name='title',
            field=models.CharField(max_length=264),
        ),
    ]
